= Conception


Il faut rappeller que ces principes à tous les niveaux
- Conception générale
- Design
- Codage

A l'echelle d'un pipeline, d'un module, d'une classe, d'une simple fonction.

Ce sont des lignes de conduites

//tag::include[]


{counter2:design_counter}


[.subsection.background]
[.center]
[%notitle]
== Dealing With Complexity

[.big]#Part {design_counter}# +
[.huge]#Dealing With Complexity#


== Dealing With Complexity


[.fragment]
--
* Complex vs Complicated ?
** _Complex_ as opposed to _simple_ => _indirect_,
** _Complicated_ as opposed to _easy_ => _difficult_.
--

[.fragment]
--
If _complexity_ is not a problem, _complication_ should be avoided.
--

[.fragment]
--
* Abstraction, Complixity, Complication
** The more _abstract_ are ideas, the more _complex_ is implementation.
** The more _complex_ is implementation, the more _complicated_ *may be* the code
--

[.fragment]
[.center]
--
[big]#Complexity#  => [.big]#Complicated#


In general, _complexity_ leads to _complication_ if you are not careful.
--

[.fragment]
--
So be careful...
--

[NOTE.notes]
--
There is always some confusion between Complex and Complicated.
Complex can be opposed to simple while complicated can be opposed to easy.
Software can be complex, because the implementation of the underlying ideas requires several steps or depths.

But such architecture is not complicated, it is just not direct.

On the contrary, a simple idea could be complicated to implement as software, could be very tricky and difficult to write, to understand.

In general, complexity leads to complication if you are not careful.


Exemple with networks
https://www.itrw.net/2016/06/27/organized-cabling-is-better-cabling-avoid-server-room-spaghetti/

--


== Dealing With Complexity

* Reduce the number of elements to take into account
* Distinguish different levels of abstraction
* Isolate and decouple elements


== Reduce the number of elements to take into account

If there's a few elements, it doesn't really matter.

[.center]
image::images/marc/good_practices-reduce_complexity_0.svg[]


[NOTE.notes]
--
In the turning idea to code, there's could be a lot of steps to follow to achieve the goals.
If there's a few elements, it doesn't really matter.

--

[transition=none]
== Reduce the number of elements to take into account

But with some more...

[.center]
image::images/marc/good_practices-reduce_complexity_1.svg[]

[transition=none]
== Reduce the number of elements to take into account

Imagine each element could be linked to a concern...

[.center]
image::images/marc/good_practices-reduce_complexity_2.svg[]

== Concern ?

A concern is a subject of interest, a goal

[.left-column]
--
* For a restaurant
** Kitchen
** Cooking
** Orders
** Payments
** Stock
** Service
** ...
--

[.right-column]
--
* For a car
** Engine
** Fuel
** GearBox
** Frame
** ..
--

[.reset-column]
--
Try to connect each element to a concern !
--

== Group by concern

[.center]
image::images/marc/good_practices-reduce_complexity_2.svg[]

[transition=none]
== Group by concern

[.center]
image::images/marc/good_practices-reduce_complexity_3.svg[]

[transition=none]
== Group by concern

[.center]
image::images/marc/good_practices-reduce_complexity_4.svg[]

[transition=none]
== Group by concern

[.center]
image::images/marc/good_practices-reduce_complexity_6.svg[]


== Separation of concern

[.center]
image::images/marc/good_practices-reduce_complexity_6.svg[width=200]

[.center]
This is, +
roughly speaking, +
the principle of +
[.huge]#Separation of Concern#.

[.center]
You didn't magically remove _all_ the complexity.

[.fragment]
[.center]
But, you have reduced _cognitively_ the number of elements ...

[.fragment]
[.center]
\... per *level of abstraction*


== Separation of concern

Grouping element by concern could be a question of point of view.


* Choose contents such as
** They have limited _intersection_,
*** _but intersection will occur._
** They are consistent and focused,
*** _Cooking and Astronomy_ is not very consistent !

[.fragment]
* In programming world :
** Module
** Package
** Namespace
** Classe

include::03_levels_of_abstraction.adoc[tag=include]

include::03_illustration_with_movie_industry.adoc[tag=include]

include::03_part_what_and_how.adoc[tag=include]

include::03_flexibility.adoc[tag=include]

include::03_stability.adoc[tag=include]

include::03_focus.adoc[tag=include]



//end::include[]
