= Conception


Il faut rappeller que ces principes à tous les niveaux
- Conception générale
- Design
- Codage

A l'echelle d'un pipeline, d'un module, d'une classe, d'une simple fonction.

Ce sont des lignes de conduites

//tag::include[]

[.inverse.background]
[.center]
[%notitle]
== Attitude

:chapter_name: Design

[.big]#Chapter {counter:main_part_counter:1}# +
[.huge]#{chapter_name}#




[.subsection.background]
[.center]
[%notitle]
== Dealing With Complexity

[.big]#{chapter_name} - Part {counter:design_counter:1}#


[.huge]#Dealing With Complexity#

== Complexity, Complication

--
* Complex vs Complicated ?
** _Complex_ as opposed to _simple_ => _indirect_,
** _Complicated_ as opposed to _easy_ => _difficult_.
--

[.fragment]
--
If [.big]*_complexity_* is not a problem, [.big]*_complication_* should be avoided.
--

[NOTE.notes]
--
There is always some confusion between Complex and Complicated.
Complex can be opposed to simple while complicated can be opposed to easy.
Software can be complex, because the implementation of the underlying ideas requires several steps or depths.

But such architecture is not complicated, it is just not direct.

On the contrary, a simple idea could be complicated to implement as software, could be very tricky and difficult to write, to understand.
--

== Complexity, Complication And Abstraction

[.center]
--
The more *_abstract_* and *_high-level_* are ideas, +
the more *_complex_* is implementation. +

_(the less *direct* to implement)_


'''

The more *_complex_* is implementation, +
the more *_complicated_* *may be* the code. +

_(the less *easy* to understand the code)_
--



[NOTE.notes]
--
In general, complexity leads to complication if you are not careful.


Exemple with networks
https://www.itrw.net/2016/06/27/organized-cabling-is-better-cabling-avoid-server-room-spaghetti/

--


== How To Deal With Complexity

[.step]
* Reduce the number of elements to take into account
* Distinguish different levels of abstraction
* Take things in order
* Isolate and decouple elements


[.subsection.background]
[.center]
[%notitle]
== Reduce The Number Of Elements To Take Into Account

Dealing With Complexity

[.huge]#Reduce The Number Of Elements To Take Into Account#

== Reduce The Number Of Elements To Take Into Account

If there's a few elements, it doesn't really matter.

[.center]
image::images/marc/good_practices-reduce_complexity_0.svg[]


[NOTE.notes]
--
In the turning idea to code, there's could be a lot of steps to follow to achieve the goals.
If there's a few elements, it doesn't really matter.

--

[transition=fade]
[%notitle]
== Reduce The Number Of Elements To Take Into Account

But with some more...

[.center]
image::images/marc/good_practices-reduce_complexity_1.svg[]

[transition=fade]
[%notitle]
== Reduce The Number Of Elements To Take Into Account

Imagine each element could be linked to a concern...

[.center]
image::images/marc/good_practices-reduce_complexity_2.svg[]

== Concern ?

A concern is a subject of interest, a goal

[.left-column]
--
[.ppt]
* For a restaurant
** Kitchen
** Cooking
** Orders
** Payments
** Stock
** Service
** ...
--

[.right-column]
--
[.ppt]
* For a car
** Engine
** Fuel
** GearBox
** Frame
** ..
--

[%notitle]
== Reduce The Number Of Elements To Take Into Account

[.center]
image::images/marc/good_practices-reduce_complexity_2.svg[]

[transition=fade]
[%notitle]
== Reduce The Number Of Elements To Take Into Account

Group them by _concern_

[.center]
image::images/marc/good_practices-reduce_complexity_3.svg[]

[transition=fade]
[%notitle]
== Reduce The Number Of Elements To Take Into Account

Group them by _concern_

[.center]
image::images/marc/good_practices-reduce_complexity_4.svg[]

[transition=fade]
[%notitle]
== Reduce The Number Of Elements To Take Into Account

Group them by _concern_

[.center]
image::images/marc/good_practices-reduce_complexity_6.svg[]


[%notitle]
== Separation of concern

[.center]
image::images/marc/good_practices-reduce_complexity_6.svg[width=300]

[.center]
This is, +
roughly speaking, +
the principle of +
[.huge]#Separation of Concern#.

[.center]
You didn't magically remove _all_ the complexity.

[.fragment]
[.center]
But, you have reduced _cognitively_ the number of elements ...

[.fragment]
[.center]
\... per *level of abstraction*


== Separation of concern

Grouping element by concern could be *a question of point of view*.

[.fragment]
* Choose concerns such as
** They have *limited _intersection_*,
*** _but intersection will occur._
** They are *consistent* and *focused*,
*** _Cooking and Astronomy_ is not very consistent !

[.fragment]
[.ppt]
* In programming world =>
** _Module_
** _Package_
** _Namespace_
** _Classe_

include::03_levels_of_abstraction.adoc[tag=include]

include::03_illustration_with_movie_industry.adoc[tag=include]

include::03_part_what_and_how.adoc[tag=include]

include::03_flexibility.adoc[tag=include]

include::03_stability.adoc[tag=include]

include::03_focus.adoc[tag=include]

== Sump Up of Design


*A REFAIRE* Reprendre ici les principes énoncés.


Separation of Concern

Differentiation of Levels Of Abstraction

Only take into account contract

Segrg


SOLID


//end::include[]
