= Focus

//tag::include[]

[.subsection.background]
[.center]
[%notitle]
== Focus

[.big]#{chapter_name} - Part {counter:design_counter:1}#

[.huge]#Focus#


== Focus



*A REFAIRE*

* Single Responsability


[transition=fade]
[%notitle]
== Single Responsability 0


[.left-column]
[.center]
--
image::images/marc/flexibility-SingleResponsability_0.svg[width=600]
--

[.right-column]
--
Imagine our professional camera again.

It is composed of following components.
--

[transition=fade]
[%notitle]
== Single Responsability 1


[.left-column]
[.center]
--
image::images/marc/flexibility-SingleResponsability_1.svg[width=600]
--

[.right-column]
--
Designers have to modify the video component to fix a driver bug.
--

[transition=fade]
[%notitle]
== Single Responsability 2


[.left-column]
[.center]
--
image::images/marc/flexibility-SingleResponsability_2.svg[width=600]
--

[.right-column]
--
As there's only one concerned by the video _concern_, it's the only one component needing to be modified.
--

[transition=fade]
[%notitle]
== Single Responsability 3


[.left-column]
[.center]
--
image::images/marc/flexibility-SingleResponsability_3.svg[width=600]
--

[.right-column]
--
_Video_ is composed of _Optic_ and _Driver_ components  at next sub-level.
--

[transition=fade]
[%notitle]
== Single Responsability 4


[.left-column]
[.center]
--
image::images/marc/flexibility-SingleResponsability_4.svg[width=600]
--

[.right-column]
--
As it's a _video's driver_ bug, at the sub-level, there's only the _Driver_ component to be modified.
--

[transition=fade]
[%notitle]
== Single Responsability 4

[.center]
--
This is an illustration of +
[.huge]#Single Responsability# +
principle.
--

[quote]
____

Component should have a single responsibility and thus only a single reason to change.
____



[transition=fade]
[%notitle]
== Single Responsability 5


[.left-column]
[.center]
--
image::images/marc/flexibility-SingleResponsability_5.svg[width=600]
--

[.right-column]
--
Let's see a violotaion of this principle.
--


[transition=fade]
[%notitle]
== Single Responsability 6


[.left-column]
[.center]
--
image::images/marc/flexibility-SingleResponsability_6.svg[width=600]
--

[.right-column]
--
There's two bugs to correct of different concerns.
--

[transition=fade]
[%notitle]
== Single Responsability 7


[.left-column]
[.center]
--
image::images/marc/flexibility-SingleResponsability_7.svg[width=600]
--

[.right-column]
--
It appends there's two _reasons_ to modify a component, with all the potential problems.
--

== Single Responsability conclusion

*A REFAIRE* Limit required knowledge of external by keeping focused on what a component has to do.




//end::include[]
