= 03 flexibility 02 _soi

//tag::include[]

[.center]
== Show only what's is needed


[transition=fade]
[%notitle]
== Show only what's is needed


[.left-column]
--
[.center]
image::images/marc/flexibility-segregation_0.svg[width=600]

[source,python]
----
class ReportingCamera:

	def start_video(self):
		...
	def stop_video(self):
		...
	def start_sound(self):
		...
	def stop_sound(self):
		...
----
--

[.center]
[.right-column]
--


A TV _Reporting Camera Operator_ +
use a +
_Reporting Camera_ +
described by a +
_Reporting Camera Interface_.

[.fragment]
It records
_video_
and
_sound_.
--


[transition=fade]
[%notitle]
== Show only what's is needed


[.left-column]
[.center]
--
image::images/marc/flexibility-segregation_0.1.svg[width=600]
--

[.right-column]
[.center]
--
Someone decided to split +
_Reporting Camera Operator_ +
responsabilities +
in two parts.
--

[transition=fade]
[%notitle]
== Show only what's is needed


[.left-column]
[.center]
--
image::images/marc/flexibility-segregation_0.svg[width=600]
--

[.right-column]
[.center]
--
They use the same interface.
--

[transition=fade]
[%notitle]
== Show only what's is needed


[.left-column]
[.center]
--
image::images/marc/flexibility-segregation_2.svg[width=600]
--

[.right-column]
[.center]
--
They use the same interface.
--

[transition=fade]
[%notitle]
== Show only what's is needed


[.left-column]
[.center]
--
image::images/marc/flexibility-segregation_3.svg[width=600]
--

[.right-column]
[.center]
--
But if the camera itself is separated into two components...

We get a nonsense...

*We show too much.*
--

[transition=fade]
[%notitle]
== Show only what's is needed


[.left-column]
--
[.center]
image::images/marc/flexibility-segregation_4.svg[width=600]

[source,python]
----
class Video(ABC):
	@abstractmethod
	def start_video(self):
		...
	@abstractmethod
	def stop_video(self):
		...

class Microphone(ABC):
	@abstractmethod
	def start_sound(self):
		...
	@abstractmethod
	def stop_sound(self):
		...
----


--

[.right-column]
[.center]
--
We have to limit each of them +
to *WHAT* they do +
and *only* what they do.

*No more and no less.*
--



[transition=fade]
[%notitle]
== Show only what's is needed


[.left-column]
[.center]
--
image::images/marc/flexibility-segregation_5.svg[width=600]
--

[.right-column]
[.center]
--
This way, any dependency +
satisfying the interfaces +
could be used.
--

[transition=fade]
[%notitle]
== Show only what's is needed


[.left-column]
[.center]
--
image::images/marc/flexibility-segregation_6.svg[width=600]
--

[.right-column]
[.center]
--
This way, any dependency +
satisfying the interfaces +
could be used.
--


[transition=fade]
[%notitle]
== Show only what's is needed


[.left-column]
[.center]
--
image::images/marc/flexibility-segregation_6.1.svg[width=600]
--

[.right-column]
[.center]
--
What about our _Reporting Camera Operator_ ? +

It could use the both interfaces.

Whether it's implemented by _two_ components...
--


[transition=fade]
[%notitle]
== Show only what's is needed


[.left-column]
[.center]
--
image::images/marc/flexibility-segregation_6.2.svg[width=600]
--

[.right-column]
[.center]
--
\... or implemented by _only one_ component !

We don't care.
--





[transition=fade]
[%notitle]
== Show only what's is needed

[.left-column]
[.center]
--
image::images/marc/flexibility-segregation_6.before.2.b.svg[width=600]
--

[.right-column]
[.center]
--
What about the _Reporting camera_ interface ?
--


[transition=fade]
[%notitle]
== Show only what's is needed

[.left-column]
[.center]
--
image::images/marc/flexibility-segregation_6.before.2.b.svg[width=600]
--

[.right-column]
[.center]
--
How to reconcile the two universes ?
--


[transition=fade]
[%notitle]
== Show only what's is needed

[.left-column]
--
[.center]
image::images/marc/flexibility-segregation_6.before.2.svg[width=600]

--

[.right-column]
[.center]
--
By making _Reporting camera_ +
be a _Camera interface_ +
*and* +
a _Microphone interface_ too.
--


[transition=fade]
[%notitle]
== Show only what's is needed

[.left-column]
--
[.center]
image::images/marc/flexibility-segregation_7.svg[width=600]

[source,python]
----
class ReportingCamera(Camera,Microphone):
	...
----

--

[.right-column]
[.center]
--
By making _Reporting camera_ +
be a _Camera interface_ +
*and* +
a _Microphone interface_ too.
--


[transition=fade]
[%notitle]
== Show only what's is needed


[.center]
--
image::images/marc/flexibility-segregation_6.before.2.svg[width=600]
--

[.center]
--
A interface with *too much information* +
is split into very _user focused_ interfaces.

[.fragment]
It's the +
[.huge]#Segregation of Interfaces# +
principle.
--


[transition=fade]
[%notitle]
== Show only what's is needed


[.center]
--
image::images/marc/flexibility-segregation_6.3.svg[width=600]

So it
could be seen as a +
_video interface_ for video interested users.
--



[transition=fade]
[%notitle]
== Show only what's is needed


[.center]
--
image::images/marc/flexibility-segregation_6.4.svg[width=600]


\...or a
_Microphone interface_ for sound interested users.
--



[transition=fade]
[%notitle]
=== Show only what's is needed


[.left-column]
[.center]
--
image::images/marc/flexibility-segregation_8.svg[width=600]
--

[.right-column]
--
It allows very flexible architecture like this...
--



[.reset-column]
[source,python]
----
class FonyStreet(ReportingCamera):

	# microphone interface

	def start_sound(self):
		...
----


[transition=fade]
[%notitle]
=== Show only what's is needed


[.left-column]
[.center]
--
image::images/marc/flexibility-segregation_9.svg[width=600]
--

[.right-column]
--
\... or this with a delegation to the microphone for all the _Microphone stuff_.


--

[.reset-column]
[source,python]
----
class FonyStreet(ReportingCamera):

	def __init__(self, connected_microphone):
		self.microphone = connected_microphone

	# microphone interface

	def start_sound(self):
		self.microphone.start_sound() # <- delegation pattern
----



[transition=fade]
[%notitle]
=== Show only what's is needed


[.left-column]
[.center]
--
image::images/marc/flexibility-segregation_10.svg[width=600]
--

[.right-column]
[.center]
--
*Segregation Of Interfaces* allows +
to join different universes +
with different point of view.

Here the _TV universe_ +
and +
the camera _Manufacturer Universe_.
--


//end::include[]
