= Focus

//tag::include[]


== SingeResponsability 0


[.left-column]
[.center]
--
image::images/marc/flexibility-SingleResponsability_0.svg[width=600]
--

[.right-column]
--
Imagine
--

== SingeResponsability 1


[.left-column]
[.center]
--
image::images/marc/flexibility-SingleResponsability_1.svg[width=600]
--

[.right-column]
--
Imagine
--

== SingeResponsability 2


[.left-column]
[.center]
--
image::images/marc/flexibility-SingleResponsability_2.svg[width=600]
--

[.right-column]
--
Imagine
--

== SingeResponsability 3


[.left-column]
[.center]
--
image::images/marc/flexibility-SingleResponsability_3.svg[width=600]
--

[.right-column]
--
Imagine
--

== SingeResponsability 4


[.left-column]
[.center]
--
image::images/marc/flexibility-SingleResponsability_4.svg[width=600]
--

[.right-column]
--
Imagine
--

== SingeResponsability 5


[.left-column]
[.center]
--
image::images/marc/flexibility-SingleResponsability_5.svg[width=600]
--

[.right-column]
--
Imagine
--


== SingeResponsability 6


[.left-column]
[.center]
--
image::images/marc/flexibility-SingleResponsability_6.svg[width=600]
--

[.right-column]
--
Imagine
--

== SingeResponsability 7


[.left-column]
[.center]
--
image::images/marc/flexibility-SingleResponsability_7.svg[width=600]
--

[.right-column]
--
Imagine
--




//end::include[]
