= Separation of level of abstraction

//tag::include[]

[.subsection.background]
[.center]
[%notitle]
== Separate Levels Of Abstraction

Dealing With Complexity

[.huge]#Separate Levels Of Abstraction#

== Separate Levels Of Abstraction

Let us take two areas of concern.

[.center]
image::images/marc/good_practices-level_complexity_2_0.svg[width=600]


[transition=fade]
== Separate Levels Of Abstraction

[.left-column]
[.center]
image::images/marc/good_practices-level_complexity_2_1.svg[width=600]

[.right-column]
--
Several layers of abstraction, +
from the general concepts +
to the specialized components.
--

[transition=fade]
== Separate Levels Of Abstraction

[.left-column]
[.center]
image::images/marc/good_practices-level_complexity_2_1_bis.svg[width=600]


--
Several elements +
per level of abstraction.
--

[transition=fade]
== Separate Levels Of Abstraction

[.left-column]
[.center]
image::images/marc/good_practices-level_complexity_2_2.svg[width=600]


[.right-column]
--
They could be grouped by sub-concern.
--

[transition=fade]
== Separate Levels Of Abstraction

[.left-column]
[.center]
image::images/marc/good_practices-level_complexity_2_3.svg[width=600]


[.right-column]
--
They interact inside a concern, from level to another one, between concerns.
--

[transition=fade]
== Separate Levels Of Abstraction

[.left-column]
[.center]
image::images/marc/good_practices-level_complexity_2_4.svg[width=600]

[.right-column]
--
But one of the best way of doing +
is to interact +
through the top levels...
--


[transition=fade]
== Separate Levels Of Abstraction

[.left-column]
[.center]
image::images/marc/good_practices-level_complexity_blackboxes.svg[width=600]

[.right-column]
--
\... Such as black boxes +
whose contents +
can be more freely modified.

It provides more *isolation*.
--

//end::include[]
