== 03 think components

//tag::include[]

[.subsection.background]
[.center]
[%notitle]
== Think Components

Dealing With Complexity

[.huge]#Think Components#


[transition=fade]
[%notitle]
== tsam 0
[.left-column.center]
--
image::images/marc/writing-think-modular_0.svg[]
--

[.right-column]
[.center]
--
A processing (function, method) takes inputs and return ouputs.
--

[transition=fade]
[%notitle]
== tsam 1
[.left-column.center]
--
image::images/marc/writing-think-modular_1.svg[]
--

[.right-column]
[.center]
--
It could composed of sub-processings
--

[transition=fade]
[%notitle]
== tsam 2
[.left-column.center]
--
image::images/marc/writing-think-modular_2.svg[]
--

[.right-column]
[.center]
--
Each of them using results of preceding.
--


[transition=fade]
[%notitle]
== tsam 3.a
[.left-column.center]
--
image::images/marc/writing-think-modular_3.a.svg[]
--

[.right-column]
[.center]
--
If we want to look at a part, +
as it is delimitated, +
we can isolate it and focus...
--

[transition=fade]
[%notitle]
== tsam 3
[.left-column.center]
--
image::images/marc/writing-think-modular_3.svg[]
--

[.right-column]
[.center]
--
Modify it...
--

[transition=fade]
[%notitle]
== tsam 4
[.left-column.center]
--
image::images/marc/writing-think-modular_4.svg[]
--

[.right-column]
[.center]
--
And put it under test.

We can test it **independantly** +
of others.
--


[transition=fade]
[%notitle]
== tsam 4b
[.left-column.center]
--
image::images/marc/writing-think-modular_4b.svg[]
--

[.right-column]
[.center]
--
If we are interested to another part of this processing...
--

[transition=fade]
[%notitle]
== tsam 5
[.left-column.center]
--
image::images/marc/writing-think-modular_5.svg[]
--

[.right-column]
[.center]
--
Modify it, put under test it and only it.

*independantly* of other ones.

--

[transition=fade]
[%notitle]
== tsam 6
[.left-column.center]
--
image::images/marc/writing-think-modular_6.svg[]
--

[.right-column]
[.center]
--
What if the main processing is not broken down into small parts ?
--

[transition=fade]
[%notitle]
== tsam 7
[.left-column.center]
--
image::images/marc/writing-think-modular_7.svg[]
--

[.right-column]
[.center]
--
To test a portion, ...
--

[transition=fade]
[%notitle]
== tsam 8
[.left-column.center]
--
image::images/marc/writing-think-modular_8.svg[]
--

[.right-column]
[.center]
--
\... we have to put the *WHOLE* processing under test.

--

[transition=fade]
[%notitle]
== tsam 9
[.left-column.center]
--
image::images/marc/writing-think-modular_9.svg[]
--

[.right-column]
[.center]
--
And to test _another_ portion, we have to put +
the *WHOLE* processing under test _again_!
--

[transition=fade]
[%notitle]
== tsam 10
[.left-column.center]
--
image::images/marc/writing-think-modular_10.svg[]
--

[.right-column]
[.center]
--
And if test fails, +
which part is incorrect ?
--

[transition=fade]
[%notitle]
== tsam 11
[.left-column.center]
--
image::images/marc/writing-think-modular_11.svg[]
--

[.right-column]
[.center]
--
Test can not tell, as it tests the *WHOLE* processing.
--

[transition=fade]
[%notitle]
== tsam 12
[.left-column.center]
--
image::images/marc/writing-think-modular_12.svg[]
--

[.right-column]
[.center]
--
And as portions are not isolated from each other...
--

[transition=fade]
[%notitle]
== tsam 13
[.left-column.center]
--
image::images/marc/writing-think-modular_13.svg[]
--

[.right-column]
[.center]
--
Modification of an non-isolated portion of code +
could have side effects on the whole block.
--


[transition=fade]
[%notitle]
== tsam 13


[.left-column.center]
--
Good :)

image::images/marc/writing-think-modular_2.svg[]
--


[.right-column.center]
--
Bad :(

image::images/marc/writing-think-modular_6.svg[]
--

[%notitle]
== Conclusion

[.huge]
[.center]
--
Think of your code as
_small_ +
_isolated_, +
reusable +
*components*.
--


[.center]
== Very Bad

include::_god_class.adoc[tag=include]

[transition=fade]
== Ok, how to do ?

Going from...

[.left-column.center]
--
Bad legacy

image::images/marc/writing-think-modular_6.svg[]
--


[transition=fade]
== Ok, how to do ?

To
[.right-column.center]
--
Good refactoring

image::images/marc/writing-think-modular_2.svg[]
--



include::_refactor_big_block_as_small_components.adoc[tag=include]

//end::include[]
