== 04_think_small_and_modular.adoc

//tag::include[]

[transition=fade]
== tsam 0
[.left-column.center]
--
image::images/marc/writing-think-modular_0.svg[]
--

[.right-column]
--
A processing (function, method) takes inputs and out ouputs.
--

[transition=fade]
== tsam 1
[.left-column.center]
--
image::images/marc/writing-think-modular_1.svg[]
--

[.right-column]
--
It could composed of sub-processings
--

[transition=fade]
== tsam 2
[.left-column.center]
--
image::images/marc/writing-think-modular_2.svg[]
--

[.right-column]
--
Each of them using results of preceding.
--

[transition=fade]
== tsam 3
[.left-column.center]
--
image::images/marc/writing-think-modular_3.svg[]
--

[.right-column]
--
If we want to look at a part of this processing, as it is isolated, we can extract it...
--

[transition=fade]
== tsam 4
[.left-column.center]
--
image::images/marc/writing-think-modular_4.svg[]
--

[.right-column]
--
And put this processing under test, +
to test it *and only* it +
[.huge]#independantly# +
of preceding or succeding.

We try inputs and make assertions about expected outputs.

As a kind of black box.
--


[transition=fade]
== tsam 4b
[.left-column.center]
--
image::images/marc/writing-think-modular_4b.svg[]
--

[.right-column]
--
If we are interested to another part of this processing...
--

[transition=fade]
== tsam 5
[.left-column.center]
--
image::images/marc/writing-think-modular_5.svg[]
--

[.right-column]
--
We can put under test to test it and only it.

[.huge]#Independantly# of other ones.

--

[transition=fade]
== tsam 6
[.left-column.center]
--
image::images/marc/writing-think-modular_6.svg[]
--

[.right-column]
--
What if the main processing is not broken down into small parts ?
--

[transition=fade]
== tsam 7
[.left-column.center]
--
image::images/marc/writing-think-modular_7.svg[]
--

[.right-column]
--
To test a portion, ...
--

[transition=fade]
== tsam 8
[.left-column.center]
--
image::images/marc/writing-think-modular_8.svg[]
--

[.right-column]
--
\... we have to put the *WHOLE* processing under test.

--

[transition=fade]
== tsam 9
[.left-column.center]
--
image::images/marc/writing-think-modular_9.svg[]
--

[.right-column]
--
And to test _another_ portion, we have to put +
the *WHOLE* processing under test _again_!
--

[transition=fade]
== tsam 10
[.left-column.center]
--
image::images/marc/writing-think-modular_10.svg[]
--

[.right-column]
--
And if test fails, +
which part is incorrect ?
--

[transition=fade]
== tsam 11
[.left-column.center]
--
image::images/marc/writing-think-modular_11.svg[]
--

[.right-column]
--
Test can not tell, as it test the *WHOLE* processing.
--

[transition=fade]
== tsam 12
[.left-column.center]
--
image::images/marc/writing-think-modular_12.svg[]
--

[.right-column]
--
And as portions are not isolated from each other...
--

[transition=fade]
== tsam 13
[.left-column.center]
--
image::images/marc/writing-think-modular_13.svg[]
--

[.right-column]
--
Modification of an non-isolated portion of code could have side effects on the whole bloc.
--


[transition=fade]
== tsam 13


[.left-column.center]
--
Good :)

image::images/marc/writing-think-modular_2.svg[]
--


[.right-column.center]
--
Bad :(

image::images/marc/writing-think-modular_6.svg[]
--

== tsam 14.a

[.center]
--
In fact, we need to extract block as function in order to handle them.
--

[.center]
--
image::images/marc/writing-think-modular_14.a.svg[]
--



[transition=fade]
== tsam 14
[.left-column.center]
--
image::images/marc/writing-think-modular_14.svg[]
--

[.right-column]
--
How do we break a plain old bunch of code lines down into external functions ?
--

[transition=fade]
== tsam 15
[.left-column.center]
--
image::images/marc/writing-think-modular_15.svg[]
--

[.right-column]
--
The comments my friend ! +
The comments...

They tell to your brain what the stack of code lines is doing.

They _translate_ code to human world.
--

[transition=fade]
== tsam 16
[.left-column.center]
--
image::images/marc/writing-think-modular_16.svg[]
--

[.right-column]
--
They often separate _de facto_ blocks.
--


[transition=fade]
== tsam 16

[.center]
--
With a few modification, from a block you get a function easily.
--

[.center]
--
image::images/marc/writing-think-modular_16.1.svg[]
--

[transition=fade]
== tsam 17
[.left-column.center]
--
image::images/marc/writing-think-modular_17.svg[]
--

[.right-column]
--
Illustration with the burger recipe !
--


[transition=fade]
== tsam 18
[.left-column.center]
--
image::images/marc/writing-think-modular_18.svg[]
--

[.right-column]
--

--


[transition=fade]
== tsam 19
[.left-column.center]
--
image::images/marc/writing-think-modular_19.svg[]
--

[.right-column]
--
Your recipe must have comments to remember what are we doing.
--


[transition=fade]
== tsam 20
[.left-column.center]
--
image::images/marc/writing-think-modular_20.svg[]
--

[.right-column]
--
From each comment, build a _meaningful_ function name !
--

[transition=fade]
== tsam 20.1
[center]
--
image::images/marc/writing-think-modular_20.1.svg[]
--

[.center]
--
Move code bloc to a new definition named after _meaningful_ function name you found.

Modify a litle bit the code to isolate it.

(i.e no external dependencies, only parameters)
--


[transition=fade]
== tsam 20.2
[.center]
--
image::images/marc/writing-think-modular_20.2.svg[]
--

[.center]
--
The same with the next block.
--

[transition=fade]
== tsam 21


[.center]
--
At the end yo have a well defined architecture.
--

[.center]
image::images/marc/writing-think-modular_21.svg[]


//end::include[]
