= Intro

//tag::include[]

== Why Do We Produce Software ?

[NOTE.notes]
--
* Software are just tool for a lot of you.
* Tool -> to achieve objectives, goals.
* There is a link between a idea, a need and a software.
--

== What Are The Difficulties With Software Building ?

[NOTE.notes]
--
* Software is a kind of intellectual construction
** Software is a piece of distributed knowledge all over files, processes and so on
* Software is a translation "Traduttore, traditore"
** _Translator, traitor_
** How to do not lost ou betray the original goals ?
* Software is an investissment
** Software is ever in evolution, it is not written  in one and unique time, it still evolving, like a very strange kind of animal, adapting to new needs or ideas, and like in darwin evolution, still  keeping some odd and old features, artefacts or piece of useless codes.
**  So make it running is not enough.
--


== What Are The Good Practices ?

[NOTE.notes]
--
* People have been building software for 40 years.
* People gather a pretty big set of principles, recipes, experiences built by severals years of try and fail.
* Unless you're a genius, it's worth it to start using them before creating your own path.
--

//end::include[]
