== Reminder : component and interface

[NOTE.notes]
--
Est-il vraiment nécessaire de faire ce rappel ?
Je pense que oui.
--

== Separation of concern

* A software may have several concerns or responsabilities.
* Experienced says a component must not mix responsabilities
** It's not a good practice to have a Gardener-Driver
** It's akward to design, to test, to link to the original ideas

_Mettre un graphique de type nuage de mots ou réutiliser le graphique du WBS ?_

_Mettre un graphique de type cuisine avec un gros bloc d'accessoire mélangés_
_Couteau suisse multiforme grotesque_


== Single Responsability

_Mettre la petite phrase sur la nécessité de changer en 1 seul composant_


== Loosen Coupling



== SOLID ?

En fait SOLID est une application des principes généraux énoncés

=== Single Responsability

=== Open For Extension, Closed For Modification

* Orienté déploiement d'une solution
* Notion d'investissement sur une base saine, testée, validée.
* "Le composant a été testé, validé, il est reconnu."
* "Le composant n'est pas de la responsabilité du développeur."
** Le développeur ne peut que l'utiliser
** Le composant est partagé et ne peut être modifié librement
** Il n'y a pas d'engagement en dehors de l'interface
* "je ne sais pas ce qu'il va advenir (en dehors de mon influence, en dehors de mon instant présent) du composant.


=== Principle of substitution de L.

* Quand vous pensez à utiliser un composant, vous ne devez pas faire d'hypothèse sur la nature du composant, uniquement sur le contrat que le composant revendique.
* Le contrat repose entièrement sur cette notion
* Si un composant plus spécialisé, avec une nature différente *mais les mêmes engagements* est utilisé en lieu et place du premier, il ne doit y avoir aucune modification.

En fait ce principe est un moyen de chasser l'implicite !!

Exemple des rectangles et des carrés:

* le carré implicitement introduit une contrainte qui n'est pas exprimée, à savoir une règle disant l=L

[source,python]
----
class Rectangle:

    Rectangle(self, width=0, height=0):
        self.width = width
        self.height=height
        
----


En effet, c'est une conséquence pratique du principe Open/Closed

Le principe de substitution est une garantie que les futurs composants seront compatibles avec le développement actuel.

=== Segregation of interface

* Principe en relation avec Loosen Coupling
* Ne pas programmer en fonction des composants, mais des contrats, des engagements pris.
Cela permet à chacun de pouvoir évoluer à sa guise, tant que le contrat est respecté. 


_mettre un dessin_

Une interface, c'est un engagement, une description formelle.
C'est un moyen de se donner de la liberté de faire 

* ce que l'on veut
* de définir ce que l'on veut fournir ou accepter

=> cas des langages sans interface comme python ?

L'interface n'est pas qu'un objet informatique, c'est une mise au clair.

L'interface doit se voir à travers la convention d'usage et la description faite.


== Dependency of injection


== Connaitre les patterns

Court forcément
